
GET http://localhost:8083/direccion/111
###

GET http://localhost:8083/direccion
###
POST http://localhost:8083/direccion
Content-Type:application/json
Accept:application/json

{
  "zona":"Perez ddd ",
  "calle": "calle 282",
  "numero": "1233-FF",
  "longitud": 11511,
  "latitud": 55222

}
###
DELETE http://localhost:8083/direccion/44
###
PUT http://localhost:8083/direccion
Content-Type:application/json
Accept:application/json

{
  "direccion_id": 111,
  "zona":"Perez ",
  "calle": "calle 28",
  "longitud": 1715151,
  "latitud": 2815512,
  "numero": "1233-F"
}
###