GET http://localhost:8083/imagen/101
###
GET http://localhost:8083/imagen
###
POST http://localhost:8083/imagen
Content-Type:application/json
Accept:application/json

{
  "src_imagen":"/img/imagen35.jpg",
  "nombre": "imagen3"
}
###
DELETE http://localhost:8083/imagen/1
###
PUT http://localhost:8083/imagen
Content-Type:application/json
Accept:application/json

{
  "imagen_id": 101,
  "src_imagen":"/img/imagen88.jpg",
  "nombre": "imagen88"
}
###