GET http://localhost:8083/usuario/1
###
GET http://localhost:8083/usuario
###
POST http://localhost:8083/usuario
Content-Type:application/json
Accept:application/json

{
  "tipo_usuario_id":2,
  "usuario": "usuario 6",
  "contrasena":"contrasena 6",
  "fecha_registro":"1988-09-28",
  "codigo_verificacion":"",
  "persona_id": 4
}
###
DELETE http://localhost:8083/usuario/
###
PUT http://localhost:8082/usuario
Content-Type:application/json
Accept:application/json

{
  "tipo_usuario_id":2,
  "usuario": "usuario 6",
  "contrasena":"contrasena 6",
  "fecha_registro":"1988-09-28",
  "codigo_verificacion":"",
  "persona_id": 4
}
###